services:
  php-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=dryfire_db
      - DB_USER=dryfire_user
      - DB_PASS=dryfire_pass
      - PHP_ENV=development
    depends_on:
      - mysql
    container_name: dryfire-api

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dryfire_db
      MYSQL_USER: dryfire_user
      MYSQL_PASSWORD: dryfire_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    container_name: dryfire-mysql

volumes:
  mysql_data: